### ISSUE TITLE
自定义view 无法绑定数据

### ISSUE THREAD

**Issue by hycoon** [alibaba/GaiaX#10]
在GAIAX studio 模版中编辑的自定义view 的type值 与 开源框架中处理判定是否改view是自定义view的逻辑不一致。
开源框架中 判断自定义view 的逻辑
![image](https://user-images.githubusercontent.com/13215853/164260036-c666bf60-da23-4775-9dfe-a9ff7e1fd803.png)
模版中自定义view的type 
![image](https://user-images.githubusercontent.com/13215853/164260299-9037a198-1211-4287-93f8-7199cb1be65c.png)
由于判断逻辑与自定义view的 type 值不一致，造成自定义view 无法绑定数据

**Comment by biezhihua** [comment]
经过确认，已经修复，请使用 0.1.3 版本
