### ISSUE TITLE
Stretch：布局错误，根节点设置左右边距和撑满剩余空间，效果不正确

### ISSUE THREAD

**Issue by biezhihua** [alibaba/GaiaX#131]
**描述这个问题**

布局错误，根节点设置左右边距和撑满剩余空间，效果不正确

**复现步骤**

```
{
  "id": "Image1",
  "uid": "c1f5f3240f3fc4af423ca545ebacb3b2",
  "type": "gaia-template",
  "package": {
    "id": "Image1",
    "version": "0.0.1",
    "modify-timestamp": "Mon Jul 04 2022 17:46:11 GMT+0800 (China Standard Time)",
    "constraint-size": {
      "width": 375,
      "height": 100,
      "zoom": 1
    }
  },
  "layers": [
    {
      "id": "image",
      "uid": "d5df7b6b1ba07daf1eeb0f01c87dfb80",
      "type": "image"
    }
  ]
}
```

```
#Image1 {
  height: 100px;
  background-color: primaryBackground;
  justify-content: center;
  align-items: center;
  margin-left: 12px;
  margin-right: 12px;
  flex-grow: 1;
}

#image {
  width: 100px;
  height: 100px;
  border-radius: 7px;
  background-color: primaryFillColor;
} 
```

```
{
  "data": {
    "image": {
      "value": "${data.img}"
    }
  }
}
```

**预期正确的结果**

![image](https://user-images.githubusercontent.com/6761107/177502116-c846a5db-29f0-4a7a-ab91-6b8d4bdb871b.png)

**截图**

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**

**崩溃日志**

**附加信息**

**Comment by faimin** [comment]
您好，有个疑问：布局框架为什么选择`stretch`而不是`Yoga`？ （`Rust`还有个布局框架 [taffy](https://github.com/DioxusLabs/taffy) ，目前作者维护的挺积极的）

**Comment by biezhihua** [comment]
> 您好，有个疑问：布局框架为什么选择`stretch`而不是`Yoga`？ （`Rust`还有个布局框架 [taffy](https://github.com/DioxusLabs/taffy) ，目前作者维护的挺积极的）

一开始考虑到使用`stretch`的时候主要是因为它比`Yoga`更小、更聚焦一些，专注于布局计算。

置于taffy，我们立项的时候，远在3年前，那时候还没有taffy

**Comment by faimin** [comment]
> > 您好，有个疑问：布局框架为什么选择`stretch`而不是`Yoga`？ （`Rust`还有个布局框架 [taffy](https://github.com/DioxusLabs/taffy) ，目前作者维护的挺积极的）
> 
> 一开始考虑到使用`stretch`的时候主要是因为它比`Yoga`更小、更聚焦一些，专注于布局计算。
> 
> 至于taffy，我们立项的时候，没有注意到这个库

了解了，感谢解惑
