### ISSUE TITLE
动态化模版创建时传入的这个size,是否可以支持mach_parent与wrap_content

### ISSUE THREAD

**Issue by WattledGnata** [alibaba/GaiaX#133]
动态化模版创建时传入的这个size,是否可以支持mach_parent与wrap_content

**Comment by biezhihua** [comment]
是这样的，GXMeasureSize主要是一个限制性的概念，它规定的是你GaiaX模板内容的最大显示区域，并且是非必传的。

一般来说我们有三种使用情况。

1. 固定的MesuresSize-Width和固定的MesuresSize-Height，这种情况下，如果内部的模板超出了宽度和高度，那么内容不会被显示，最终产物View就是MesuresSize-Width和MeasureSize-height。
2. 固定的MesuresSize-Width，不确定的MesuresSize-Height（不传入），这种情况下，如果内部的模板实际宽度超出了MesuresSize-width，那么超出的部分不会被显示；如果内部模板的高度能够自我撑开（具备高度）；那么最后的产物View的宽度就是MesureSize-Width，而高度就是模板通过FlexBox计算后撑开的高度。
3. 不确定的MesuresSize-Width（不传入），确定的MesuresSize-Height，这种情况下，如果内部的模板实际高度超出了MesuresSize-height，那么超出的部分不会被显示；如果内部模板的宽度能够自我撑开（具备宽度）；那么最后的产物View的宽度就是是模板通过FlexBox计算后撑开的宽度，而高度就是Measure-Height。

**Comment by biezhihua** [comment]
简单来说就是，mesureSize的宽度你不传，SDK会根据内部的内容，自己撑开一个宽度。 但是如果你传了，就会用你的宽度。

**Comment by biezhihua** [comment]
https://user-images.githubusercontent.com/6761107/177522700-99675c9b-8e71-4c20-a3a7-f99760e8fef6.mp4

**Comment by WattledGnata** [comment]
嗯,了解, 那从这个角度来看, 这个 宽高的语义与变量名稍有出入

**Comment by biezhihua** [comment]
> 嗯,了解, 那从这个角度来看, 这个 宽高的语义与变量名稍有出入

@jingcheng1988 @qiqiangqq 

感觉GXMeasureSize语义和上述的内容不太一致，GXLimitSize是不是更好一些。

**Comment by biezhihua** [comment]
解决方案：
- API名字不做调整
- 双端增加对GXMeasureSize-API的详解解释
