### ISSUE TITLE
GAIAX 普通模版类型 嵌套grid 类型模版崩溃

### ISSUE THREAD

**Issue by hycoon** [alibaba/GaiaX#14]
在demo 中，新建普通模版，嵌套grid 类型模版 如图
![image](https://user-images.githubusercontent.com/13215853/164456230-67469b7f-5aa3-41c4-bf67-fc1ab81d9647.png)
运行demo后出现崩溃
![image](https://user-images.githubusercontent.com/13215853/164456904-a73c4340-74d3-4e3d-bddb-6014d549fa58.png)
这种其普通模版是否能嵌套grid类型模版？如果能嵌套，绑定数据方面应该注意什么？

**Comment by hycoon** [comment]
demo 版本 是从 tag 0.1.0迁出的版本
复现步骤为 
1、在gaiax studio 种新建普通类型模版 
2、将gx-content-uper-grid 模版导入gaiax studio，并且 拖拽到 新建模版中
3、将普通模版 按照demo 中创建 根据模id + mock 数据 得到模版view 的流程 创建view 并展示 ，运行demo
4、出现异常
新建模版 json文件
![image](https://user-images.githubusercontent.com/13215853/164460086-4176d5ad-dbc9-45ee-8d23-25dd1d27b84b.png)

**Comment by biezhihua** [comment]
我看了下你的模板。 你实际上是想使用嵌套一个容器grid模板。 

你可以参考这个案例 

![image](https://user-images.githubusercontent.com/6761107/164584198-7d56f95a-9ffa-4a7d-b793-243b3241f94f.png)

**Comment by biezhihua** [comment]
你自己的例子，之所以报错，是因为数据传递错误了。 

模板的渲染是需要数据源的。 这是个前提。 例如A模板、B模板、C模板。

A嵌套了B、B嵌套了C。

A模板是由代码中直接设定数据源的，所以可以在A的databidning中直接写取值逻辑，赋值给节点。

那么B模板由于被嵌套在了A中，那么B该怎么取值？ 

这个时候B模板，需要由A模板，从databidning中取出一个数据源，传递给B模板。

同理，在使用容器模板的时候，也需要这么做。

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/164584222-4da6f154-f463-443a-94ce-480b27e29b63.png)

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/164584252-7efe9ac0-9303-45a2-a1d2-7ef52d27e068.png)

**Comment by biezhihua** [comment]
这种模板与模板之间的数据源的传递，的确需要注意一下。 

因为看起来就像个普通节点数据绑定一样，所以容易忽视。 

这块我们在文档之中也标注一下。

**Comment by biezhihua** [comment]
就想这种A模板嵌套了一个B容器。 

写法有两种，

 A写$$传数据给B，B自己$nodes取数组给自己赋值。
 A写$nodes传数据给B，B自己$$取数组给自己赋值

**Comment by biezhihua** [comment]
你的例子已经给gird模板传递数据源了，但是grid没有给自己绑定数据。

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/164584324-d1133b73-8233-4b24-b070-6356f5194baf.png)

**Comment by biezhihua** [comment]
我们补充下文档关于 “模板之间数据源传递及使用” 的注意事项。

**Comment by biezhihua** [comment]
https://www.yuque.com/g/biezhihua/gaiax/izbht6/collaborator/join?token=4Q1l2cjz4oV9cHIv# 《数据绑定》

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/164584445-7bab7984-85d8-42c1-9e0a-ba1a3f6865db.png)

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/164584476-3925e9f2-9ac2-4aa8-94a1-7c9a708fa3cf.png)

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/164584506-537b3b42-5fac-4e90-b51d-85ac6ab453e7.png)
