### ISSUE TITLE
安卓列表容器存在滑动性能问题

### ISSUE THREAD

**Issue by focusnews** [alibaba/GaiaX#149]
**描述这个问题**

在RecyclerView中使用gaiaX容器组件会存在滑动卡顿现象， 猜测原因是重绘制时模版重新加载导致的卡顿

**复现步骤**

可通过分步复现该问题：
1. 到什么页面 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 产生错误

**预期正确的结果**

请清晰和简明的描述你预期正确的结果。

**截图**

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [e.g. 0.1.0]
 - Gaia Studio版本 [e.g. 0.1.0]
 - GaiaX 模板文件和模板数据

**崩溃日志**
在这里添加崩溃日志

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by biezhihua** [comment]
https://github.com/alibaba/GaiaX/pull/341
