### ISSUE TITLE
iOS 循环引用问题

### ISSUE THREAD

**Issue by ifwrite** [alibaba/GaiaX#158]
<img width="1326" alt="image" src="https://user-images.githubusercontent.com/13459701/180917356-eb52d468-ba85-4bde-89ce-ee7c6bd09421.png">
请问老师，这种如何避免循环引用？

**Comment by jingcheng1988** [comment]
> <img alt="image" width="1326" src="https://user-images.githubusercontent.com/13459701/180917356-eb52d468-ba85-4bde-89ce-ee7c6bd09421.png">
> 
> 请问老师，这种如何避免循环引用？

问题已经修复，感谢反馈~

**Comment by jingcheng1988** [comment]
> <img alt="image" width="1326" src="https://user-images.githubusercontent.com/13459701/180917356-eb52d468-ba85-4bde-89ce-ee7c6bd09421.png">
> 
> 请问老师，这种如何避免循环引用？

问题已经修复，感谢反馈~
