### ISSUE TITLE
gaiax中添加editText，输入法弹出到时候不能自动把底部view一起顶上去

### ISSUE THREAD

**Issue by songw9s8x7** [alibaba/GaiaX#162]
**描述这个问题**

原声android中，如果使用RelativeLayout或者ConstrainLayout，activity使用到inputMethodconfig使用resize或者pan的时候，
布局中 属性为app:layout_constraintBottom_toBottomOf="parent"的view，在输入法弹出的时候能够自动和输入法一起上移，但是gaiax中无法实现这个效果

**截图**

![image](https://user-images.githubusercontent.com/7436903/181436291-26b8e912-784a-4ce0-a1c1-f0c349d5c665.png)
这是想要实现的效果，但是gaiax中貌似没发实现

**Comment by biezhihua** [comment]
https://github.com/songw9s8x7/GaiaX/tree/issue

**Comment by fullalien** [comment]
由于 GaiaX SDK 每次渲染出来的是绝对布局，没有用到约束，当显示区域 Size 变化后，需要重新 binding 更新视图，因此为了更好的体验，建议拆分实现，比如底部功能区可拆分为一个 GaiaX 模版
GaiaX 更适用于实现相对显示区域 Size 不会改变的情景
更多可参考：[GaiaXSDK 文档](https://www.yuque.com/biezhihua/gaiax/kibtop)
