### ISSUE TITLE
加载远程模板

### ISSUE THREAD

**Issue by wudongze** [alibaba/GaiaX#164]
加载远程模板后能得到一个GXTemplate对象，但是gaiax加载模板需要GXTemplateItem对象，GXTemplate这个怎么转换GXTemplateItem，还是gaiax可以直接加载GXTemplate呢

**Comment by biezhihua** [comment]
GXTemplate到GXTemplateItem的转换在内部，你可以看GXTemplateInfoSource.getTemplateInfo方法。

原始模板解析成GXTemplate，你可以看GXAssetsBinaryWithoutSuffixTemplate.createTemplate和GXAssetsTemplate.的这个方法

**Comment by biezhihua** [comment]
模板这块是两个步骤。

一个是明文模板到GXTemplate的转换，你这接入远程模板，主要是针对这块进行操作，提供一个数据源。

一个是GXTemplate到GXTemplateItem的转换，将字符串转换为Entity。

**Comment by biezhihua** [comment]
GXTemplate代表模板的原始字符串。

GXTemplateInfo代表由模板原始字符串转换来的Entity类。

GXTemplateItem代表你想要加载的模板信息，里面包含了模板的ID和业务ID。

这三个是不同的东西。

如果你需要注册一个远程模板的数据源，你只需要实现GXRegisterCenter.GXIExtensionTemplateSource接口，并注入到数据源中即可。不需要其他额外的操作。
