### ISSUE TITLE
和手淘的DinamicX很像，是借鉴的DX吗？后续是否有融合的计划？

### ISSUE THREAD

**Issue by Yang9322** [alibaba/GaiaX#17]
**描述这个问题 **

请清晰和简明的描述这个问题。

**复现步骤 - **

可通过分步复现该问题：
1. 到什么页面 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 产生错误

**预期正确的结果**

请清晰和简明的描述你预期正确的结果。

**截图**

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [e.g. 0.1.0]
 - GaiaX 模板文件和模板数据

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by qiqiangqq** [comment]
你好，GaiaX与DX解决的问题有相似性，因此整体实现方案也类似，如都有跨端DSL，都是本地Native渲染，但GaiaX技术方案是优酷技术团队自行设计的。目前在IDE上跟DX团队有合作共建，SDK融合的难度很大，暂时不会往这个方向发展。

**Comment by Yang9322** [comment]
好的，谢谢~
