### ISSUE TITLE
特性：手动埋点支持

### ISSUE THREAD

**Issue by jiyuegongzi** [alibaba/GaiaX#176]
**描述这个问题**

当前gaiax模块不能很好地支持内部控件级别的曝光，比如我的某个gaiax模块里面有横排的三个item，我的曝光埋点需要做到item级别。当前曝光了一个item还是两个item。

**复现步骤**
必先

**预期正确的结果**

比如我的模块中只有三个item， 但是只有两个item在可视范围内。 我的应用从后台到前台的时候，我的曝光能够上报两个item的曝光。

**截图**

![image](https://user-images.githubusercontent.com/11285176/182550573-1fc50eb8-3174-4ccb-ac2e-5020874bc7e1.png)

**Comment by biezhihua** [comment]
技术方案：https://www.yuque.com/biezhihua/gaiax/ld6iie
开发时间：8月19日前
