### ISSUE TITLE
依赖的compileSdkVersion版本问题

### ISSUE THREAD

**Issue by zchong816** [alibaba/GaiaX#18]
**描述这个问题 **

最新版本 com.github.alibaba:GaiaX:0.1.4 要求依赖的compileSdkVersion有些高要31，我们的环境最高是28能否降级发个版本呢，ps:应该不少的app都停留在相对较低的版本:)

**Comment by biezhihua** [comment]
@zchong816 这个我降级一下，然后发个新版本。

**Comment by biezhihua** [comment]
@zchong816 辛苦贴一下在compileSDKVersion 28的条件下，你们androidx的各个子包的依赖版本。

**Comment by biezhihua** [comment]
implementation "androidx.core:core-ktx:1.6.0"
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation "com.google.android.material:material:1.4.0”
    implementation 'androidx.constraintlayout:constraintlayout:2.0.4'

    implementation 'com.alibaba:fastjson:1.2.76'

    implementation project(path: ':GaiaXAndroid')
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    implementation 'androidx.lifecycle:lifecycle-livedata-ktx:2.3.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1'

//    implementation 'com.github.alibaba:GaiaX:0.1.4'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.3'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.4.0'
