### ISSUE TITLE
Feature:表达式语法问题

### ISSUE THREAD

**Issue by WattledGnata** [alibaba/GaiaX#186]
**描述这个问题**

目前使用中，发现表达式功能有如下缺陷

1. != null 这种判空，只能对字符串使用，无法对对象与数组使用： 异常表现：会崩溃
2. size(string) , size(array) 字符串取长度，或者array取长度，方法，都不兼容空对象：异常表现，崩溃
3. 三目运算符  a ? b : c  逻辑，不满足短路原则，即满足a条件为true的情况下，c逻辑依然会执行，导致无法通过a逻辑的判断来规避c中的逻辑执行。因此无法进行安全的判空取值逻辑如下

`($array[0] != null) ? size(array) : 0 `
无法使用'array[0] != null'  这样的安全判断， 来规避  size(array) 这样的风险逻辑的运行

<img width="849" alt="image" src="https://user-images.githubusercontent.com/27803450/185444083-1e30ec13-2b3f-47fe-b3d3-f0552fac9f17.png">
针对问题1，看起来是刻意把对象与数组给排除出去的，这是种什么考量，是因为有未知风险么？

对问题2，看了下，应该是安卓单端的问题。
![image](https://user-images.githubusercontent.com/27803450/185531214-d026f4c0-cc40-439b-a6ee-f4c3cadfe480.png)
因为没有一个else分支给一个默认实现，导致c++那层发生空指针

![image](https://user-images.githubusercontent.com/27803450/185531394-603c88e2-79f6-4159-8784-143fac8c4a2f.png)
ios给了个默认值0 
@biezhihua 

请清晰和简明的描述这个问题。

**复现步骤**

可通过分步复现该问题：
1. 到什么页面 '...'
5. 点击 '....'
6. 滑动到 '....'
7. 产生错误

**预期正确的结果**

请清晰和简明的描述你预期正确的结果。

**截图**

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [e.g. 0.1.0]
 - Gaia Studio版本 [e.g. 0.1.0]
 - GaiaX 模板文件和模板数据

**崩溃日志**
在这里添加崩溃日志

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by MXPDS6688** [comment]
size传null参数导致异常以及map、array无法使用==和!=操作符的问题已修复
三元运算中，如表达式：a ? b : c
a只支持true和false的结果，如果为其他输入，返回值均为false，即表达式结果为c，只有在a的结果为true时，表达式结果为b
