### ISSUE TITLE
自适应的文本，如果设置了display 为false，会异常

### ISSUE THREAD

**Issue by WattledGnata** [alibaba/GaiaX#197]
**描述这个问题**

对于自适应高度的文本，如果它或者它的父布局被设置了隐藏。 此时它被计算的宽度是0。 
同时给该文本视图设置文本。自适应Util方法会继续向下执行
而自适应高度计算的方法里，判断宽度为0后，不会判断当前视图是否可见，会直接抛出异常
![image](https://user-images.githubusercontent.com/27803450/187156665-968bddf1-1f6e-45d8-9192-bc739b73e9dc.png)

@biezhihua 

请清晰和简明的描述这个问题。

**复现步骤**

可通过分步复现该问题：
1. 到什么页面 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 产生错误

**预期正确的结果**

请清晰和简明的描述你预期正确的结果。

**截图**

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [e.g. 0.1.0]
 - Gaia Studio版本 [e.g. 0.1.0]
 - GaiaX 模板文件和模板数据

**崩溃日志**
在这里添加崩溃日志

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by biezhihua** [comment]
@WattledGnata 感谢反馈，我会尽快跟进处理
