### ISSUE TITLE
Android如何局部刷新?

### ISSUE THREAD

**Issue by leo-wxy** [alibaba/GaiaX#210]
**描述这个问题**

Android Demo项目-点击事件测试，点击关注按钮，触发`data.isFollowed`变化，导致下方列表选中位置回到初始点。
测试观察iOS是可以局部刷新，修改关注按钮状态且不影响下方列表展示效果

**预期正确的结果**

只会影响到关注按钮的显示效果，其他部分不会发生变化

**Comment by biezhihua** [comment]
@leo-wxy 这个问题我最近明天会跟进一下，然后给出反馈。

**Comment by biezhihua** [comment]
https://github.com/alibaba/GaiaX/pull/212

**Comment by biezhihua** [comment]
该问题是由双端逻辑不一致导致的，已经修复。 感谢反馈。 @leo-wxy
