### ISSUE TITLE
maven 仓库中找不到Gaiax

### ISSUE THREAD

**Issue by SpeedRn** [alibaba/GaiaX#215]
**描述这个问题**

请清晰和简明的描述这个问题。
gradle dependencies 中添加入下依赖
    implementation 'com.alibaba.gaiax:GaiaX:0.0.1'
报错如下
<img width="473" alt="image" src="https://user-images.githubusercontent.com/10684520/190408826-a9f0e77d-f2e8-4b79-8709-eed9d2e3b8f1.png">

**复现步骤**

可通过分步复现该问题：
1. 到什么页面 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 产生错误

**预期正确的结果**

请清晰和简明的描述你预期正确的结果。

**截图**

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [e.g. 0.1.0]
 - Gaia Studio版本 [e.g. 0.1.0]
 - GaiaX 模板文件和模板数据

**崩溃日志**
在这里添加崩溃日志

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by biezhihua** [comment]
请使用最新的版本 

@SpeedRn

**Comment by SpeedRn** [comment]
> 请使用最新的版本
> 
> @SpeedRn
最新版本在哪里可以看到。我在maven仓库中搜索不到gaiax。

另外看起来 gaiax 项目通过反射方式依赖了GXAdapter，而Adapter又依赖了GXAnalyzeAndroid项目。是不是必须都引入，才能正确绑定数据?
我通过localMaven方式，单独依赖Gaiax。发现能够渲染模板，但是无法绑定数据

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/190589614-043a552a-b04f-406b-990f-e80b30f12dfb.png)

**Comment by biezhihua** [comment]
```
implementation 'com.github.alibaba.GaiaX:GaiaX-Adapter:0.2.8'
implementation 'com.github.alibaba.GaiaX:GaiaX:0.2.8'
implementation 'com.alibaba:fastjson:1.2.76'
```

@SpeedRn 这样使用。可以看下Readme

**Comment by biezhihua** [comment]
> > 请使用最新的版本
> > @SpeedRn
> > 最新版本在哪里可以看到。我在maven仓库中搜索不到gaiax。
> 
> 另外看起来 gaiax 项目通过反射方式依赖了GXAdapter，而Adapter又依赖了GXAnalyzeAndroid项目。是不是必须都引入，才能正确绑定数据? 我通过localMaven方式，单独依赖Gaiax。发现能够渲染模板，但是无法绑定数据

目前需要同时依赖GaiaX和GaiaXAdapter才能正常使用GaiaX的所有功能。 

GaiaX只是通过反色的方式帮助Adapter初始化，并没有依赖里面的内容，仅仅是帮使用者节省一些操作。

**Comment by biezhihua** [comment]
GaiaX里面包含了核心功能
GaiaXAdapter包含了一些差异化的功能，例如表达式、图片、动画库等。

表达式因为优酷还没有直接使用开源的表达式逻辑，所以这块是拆分出来的。

**Comment by biezhihua** [comment]
建议先试用GaiaXDemo跑一下，里面有完整的案例，并且都是源码依赖。

**Comment by SpeedRn** [comment]
> 建议先试用GaiaXDemo跑一下，里面有完整的案例，并且都是源码依赖。

好的。源码已经跑过了，之前看的语雀文档，那里可能不是很同步。
现在正在尝试往现有工程中依赖。多谢回复
