### ISSUE TITLE
android  本地图片资源 模版local:xxxx 不生效问题

### ISSUE THREAD

**Issue by hycoon** [alibaba/GaiaX#216]
**描述这个问题**
在模版中 引用android本地图片 ，运行程序后 图片不显示

问题定位 
在模版渲染过程成中 gaiaX 会调用
![image](https://user-images.githubusercontent.com/13215853/190551026-d7968cec-cea9-4a78-9e30-235d1be88a21.png)

![image](https://user-images.githubusercontent.com/13215853/190551107-1c37fbe5-9673-4f8a-a5af-8a5be015df16.png)

![image](https://user-images.githubusercontent.com/13215853/190551153-2b6601a8-d499-4098-924f-b3c0edda0b1c.png)

这时候 本地的图片 并没有在 与模版绑定 的json 数据中，因为是本地图片，只是在模版中配置了，所以

框架中中更新节点的json数据就一直不包括 本地的资源 
![image](https://user-images.githubusercontent.com/13215853/190551742-42816a33-a0bb-4fde-b7e1-2d6e9c9a60c1.png)

![image](https://user-images.githubusercontent.com/13215853/190551809-4ca4d981-227d-47ac-a21b-af657ec96ae7.png)

![image](https://user-images.githubusercontent.com/13215853/190551870-693aa60b-2e69-4a06-8571-d405caaf6388.png)

![image](https://user-images.githubusercontent.com/13215853/190552111-83230755-5673-4508-b983-c57e5688ce98.png)

我虽然在绑定模版binddata时将本地路径拼进去但是这样动态性会有折扣，希望技术同学予以修复

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [e.g. 0.1.0]
 - Gaia Studio版本 [e.g. 0.1.0]
 - GaiaX 模板文件和模板数据

**崩溃日志**
在这里添加崩溃日志

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by biezhihua** [comment]
@hycoon 你的图片资源放在哪个文件夹下了？

**Comment by biezhihua** [comment]
目前我发现好像如果图片资源放在mipmap-xxx目录下无法正常读取
