### ISSUE TITLE
gaiaX 与支持插件化的 项目  classloader 不匹配问题

### ISSUE THREAD

**Issue by hycoon** [alibaba/GaiaX#217]
**gaiax 接入有插件化项目时，插件中 动态化模版加载插件中资源找不到**

宿主项目是插件化项目 ，在宿主项目中，我们对classloader 进行封装，插件用 PathClassloader 的子类进行加载。但是如果涉及在插件中 加载 类 或者 资源时，会出现资源加载异常的崩溃。

问题定位 
![image](https://user-images.githubusercontent.com/13215853/190553316-d66f3d9e-05a7-4347-85b5-a59c0d897f68.png)

![image](https://user-images.githubusercontent.com/13215853/190553782-3412973a-c5af-441d-b165-a97b70ea6dca.png)

![image](https://user-images.githubusercontent.com/13215853/190553503-f0489540-94ac-4cb6-8048-b207769cf38f.png)

![image](https://user-images.githubusercontent.com/13215853/190553593-2753ac5c-8982-40e2-890c-ae8f6087ddc5.png)

但是 我们的classloader 并不是 bootClassLoader 所以出现类找不到问题。
对于这种情况，如果我们项目想使用gaiax 的话，能否提供一个更适合维护的方案？
我当前的解决方案 是
在绑定模版时 提供一个监听方法 将 是否 是插件 以及对应的classloader 传给 GaiaX框架 在加载类资源时 如果发现时插件 就更换classloader
但是这样对框架侵入太大，希望有更好的方案可以替代。

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [e.g. 0.1.0]
 - Gaia Studio版本 [e.g. 0.1.0]
 - GaiaX 模板文件和模板数据

**崩溃日志**
在这里添加崩溃日志

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by biezhihua** [comment]
@hycoon 

```
initGXAdapter()?.init(context)
```

其主要目的是用来初始化GaiaXAdapter里面的扩展逻辑。 哪怕ClassLoader不同找不到类，也不会导致Crash。

你只需要自己调用`GXAdapter().init(context)`方法初始化一下就可以了。

**Comment by biezhihua** [comment]
另外，你描述的

“我当前的解决方案 是
在绑定模版时 提供一个监听方法 将 是否 是插件 以及对应的classloader 传给 GaiaX框架 在加载类资源时 如果发现时插件 就更换classloader”

这段内容我不是和理解，你可以再详细解释一下。
