### ISSUE TITLE
【Android】GXMeasureViewPool 看起来有内存泄漏风险

### ISSUE THREAD

**Issue by WattledGnata** [alibaba/GaiaX#220]
**描述这个问题**

安卓用来辅助计算文字高度的这个GXMeasureViewPool，借助的是第一次创建gaia视图所使用的context。 并且
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/27803450/190914477-99989daa-0d6e-4083-9279-a4e9cedb6cd9.png">
目前表现为，第一次创建gaia视图的那个页面的context，被这个viewpool给保存了下来，并且一直不释放。

另外一个问题，在于，这个viewpool里面保存的textView。它的context如果走完了生命周期，就不会再响应一些页面级别的回调(如字体大小的缩放)
因此，假如要适配文字的SP逻辑时，这个地方就是个隐患。

<img width="505" alt="image" src="https://user-images.githubusercontent.com/27803450/190915147-7a41905d-7f79-409e-965d-60c919df01b7.png">

**Comment by biezhihua** [comment]
1. 改为了软引用
2. 在context不一致和destroy时重新创建
3. 默认使用原始的GXText来计算，不再新创建。
