### ISSUE TITLE
问题：android GXMeasureSize限制宽高失效问题

### ISSUE THREAD

**Issue by zhupeipei** [alibaba/GaiaX#229]
GXMeasureSize 的宽高是view展示的最大值，但是我在css里宽高如果不通过百分比而是通过px指定，这时候css指定的值大于GXMeasureSize的值的话，GXMeasureSize这个限定值就会失效

可以基于demo修改复现该问题：

![修改1](https://imagev2.xmcdn.com/storages/47a3-audiofreehighqps/93/3C/GMCoOSIHCbjlAAEGcwGolWbI.png)
![修改2](https://imagev2.xmcdn.com/storages/8a48-audiofreehighqps/9C/87/GMCoOSMHCbjpAADwkwGolWgi.png)

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/192719448-c896cab4-ec5b-42ef-8888-c86eb45132c2.png)

![image](https://user-images.githubusercontent.com/6761107/192719474-213a64f7-4ee3-4db0-ac70-db7339a04090.png)

**Comment by biezhihua** [comment]
我看了下css的规范，外层px size的大小，无法限制住孩子px size的大小的，没法起到约束作用。

**Comment by biezhihua** [comment]
刚才和神梦讨论了一下。 我这边对GXMeasureSize的定义不是很准确，我们虽然描述的是一个视窗大小，但是其实从结果来看并不是一个视窗大小，GXMeasureSize本身不会生成一个新View用于承载模板View的显示。 所以导致了你这种疑惑，这块我和神梦看看怎么解释更清晰一些。 然后更新下注释。 

从目前渲染结果来看是没有问题的。

![image](https://user-images.githubusercontent.com/6761107/192727850-d756dfa2-78fb-45c7-bbf4-a4f742ed6b54.png)

**Comment by biezhihua** [comment]
因为是视窗的概念是一个独立的View，会对里面的View做截取显示。 

而GaiaX这边根据GXMeasureSize计算出模板的大小，GXMeasureSize只是个建议值，不会生成一个独立view，按照css的规范，外层px size的大小，无法限制住孩子px size的大小的，没法起到约束作用。
