### ISSUE TITLE
box-shadow拓展属性绑定失效

### ISSUE THREAD

**Issue by jiyuegongzi** [alibaba/GaiaX#262]
"box-shadow": "env('isAndroid')?'1px 1px 10px 3px #00000008':'5px 5px 4px 4px #00000030'"
拓展属性绑定失效

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/201255859-13a0d834-0dbe-407f-aaf8-0173555022bf.png)

目前只在creator的逻辑中做了样式的更新。 extend的漏掉了
