### ISSUE TITLE
同一行多个单行自适应文本时，flexShrink 属性生效

### ISSUE THREAD

**Issue by WattledGnata** [alibaba/GaiaX#267]
**描述这个问题**
[mockl两个标签.zip](https://github.com/alibaba/GaiaX/files/9988657/mockl.zip)

![image](https://user-images.githubusercontent.com/27803450/201289453-54b1d4e0-80cf-4caa-b551-aa8fa70fe2ea.png)
模版如图，在横向容器里有两个标签，都是文本标签，要求标签展示不全时展示”...“
在Android平台，对flexShrink属性没有加延时计算逻辑
![image](https://user-images.githubusercontent.com/27803450/201290669-0864078c-13df-4edf-b716-d15e9861a7fd.png)
会导致，节点会基于文本自适应之前设置的宽高，来计算自身当前可被撑开的最大宽度，导致文本展示超出父容器被截断

另外，在延时逻辑这里
![image](https://user-images.githubusercontent.com/27803450/201292446-9c5aceba-463b-4c52-992b-a1d748925801.png)
dirtyText的一次遍历，导致有依赖的自适应文本之间的宽高计算仍然没有先后关系，计算的结果中，依然是各自按照其他组件未展开时候的高度去计算的宽度

Ios的表现不一致，但看起来应该也有类似问题

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/201618438-a6884b8f-e7b7-4414-a8fc-582d36b24079.png)

**Comment by biezhihua** [comment]
.one {
    width:500px;
    height:300px;
    background-color: #9fbee0;
}
.two {
    width: 100%;
    height:200px;
    background-color: #6597cd;
}
.three {
   flex-shrink: 1;
  height:100px;
    background-color: #2c5887;
}
.three1 {
    flex-shrink: 1;
    width:200px;
    background-color: #2c5887;
}
.four {
    height:100px;
    flex-shrink: 1;
    background-color: #19324d;
}
.four1 {
    flex-shrink: 1;
    width:500px;
    background-color: #19324d;
}

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/201626098-420a7065-474e-4ce1-9b19-db1cd1c6f25a.png)

**Comment by biezhihua** [comment]
body {
    width: 95%;
    height: 100;
    margin: 0 auto;
    background-color: #2d2d2d;
}
h1,
h2,
p {
    text-align: center;
    color: #f3f3f3;
    font-family: 'Share Tech Mono', monospace;
}
h1 {
    margin: 10px;
}
.demo-wrap {
    background-color: #4e4e4f;
    height: 375px;
    width: 80%;
    margin: 0 auto;
    border: 2px solid #f3f3f3;
    border-radius: 5px;
    display: flex;
}
.box {
    background-color: #3c78b7;
    border-radius: 5px;
    margin: 5px;
    padding: 10px 10px;
    display: flex;
    justify-content: center;
    align-items: center;
}
.box p {
    font-size: .8em;
}
.one {
    width:500px;
    height:300px;
    background-color: #9fbee0;
}
.two {
    width: 100%;
    height:200px;
    background-color: #6597cd;
}
.three {
   flex-shrink: 1;
  height:100px;
    background-color: #2c5887;
}
.three1 {
    flex-shrink: 1;
    width:200px;
    height:50px;
    background-color: #00ff00;
}
.four {
    height:100px;
    flex-shrink: 1;
    background-color: #19324d;
}
.four1 {
    flex-shrink: 1;
    width:500px;
    height:50px;
    background-color: #ff00ff;
}
.property-container {
    display: flex;
    justify-content: center;
}
.property-box {
    width: 32%;
    padding: 5px;
}
.property-box h2 {
    font-size: 1.2em;
    background-color: #3c78b7;
    padding: 5px 0;
    border-radius: 5px;
    margin-top: 0;
    font-size: 1em;
}
.property-box p {
    background-color: #4e4e4f;
    padding: 3px;
    margin: 5px auto;
    width: 90%;
    border-radius: 5px;
}
.property-box .selected {
    border: 2px solid #3c78b7;
}
.fd-row {
    flex-direction: row;
}
.fd-row-reverse {
    flex-direction: row-reverse;
}
.fd-column {
    flex-direction: column;
}
.fd-column-reverse {
    flex-direction: column-reverse;
}
.jc-flex-start {
    justify-content: flex-start;
}
.jc-flex-end {
    justify-content: flex-end;
}
.jc-center {
    justify-content: center;
}
.jc-space-between {
    justify-content: space-between;
}
.jc-space-around {
    justify-content: space-around;
}
.ai-flex-start {
    align-items: flex-start;
}
.ai-flex-end {
    align-items: flex-end;
}
.ai-stretch {
    align-items: stretch;
}
.ai-center {
    align-items: center;
}
.ai-baseline {
    align-items: baseline;
}

**Comment by biezhihua** [comment]
<head>
    <link href="https://fonts.googleapis.com/css?family=Share+Tech+Mono" rel="stylesheet">
</head>

<body>
    <h1>flexbox demo</h1>
    <div class='demo-wrap ai-flex-start'>
        <div class='box one'>
            <div class='box two'>
           <div class='box three'>
                <div class='box three1'>
        </div>
        </div>
        <div class='box four'>
            <div class='box four1'>
        </div>
        </div>
        </div>
        
        </div>
       
    </div>
    <p>Toggle flexbox properties with the buttons below</p>
    <div class='property-container'>
        <div class='flex-direction-box property-box'>
            <h2>flex-direction</h2>
            <p class='f-d-r property selected'>row</p>
            <p class='f-d-r-r property'>row-reverse</p>
            <p class='f-d-c property'>column</p>
            <p class='f-d-c-r property'>column-reverse</p>

        </div>
        <div class='justify-content-box property-box'>
            <h2>justify-content</h2>
            <p class='j-c-f-s property selected'>flex-start</p>
            <p class='j-c-f-e property'>flex-end</p>
            <p class='j-c-c property'>center</p>
            <p class='j-c-s-b property'>space-between</p>
            <p class='j-c-s-a property'>space-around</p>
        </div>
        <div class='align-items-box property-box'>
            <h2>align-items</h2>
            <p class='a-i-f-s property selected'>flex-start</p>
            <p class='a-i-f-e property'>flex-end</p>
            <p class='a-i-s property'>stretch</p>
            <p class='a-i-c property'>center</p>
            <p class='a-i-b property'>baseline</p>
        </div>
    </div>
</body>

**Comment by biezhihua** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/CSS/flex-shrink

**Comment by biezhihua** [comment]
我找前端同学确认了下，你这种情况在FlexBox布局中不算BUG，flex-shrink使用的前提要求父节点必须有宽度。

但是我把你这个模板简略之后，实际上是两个文字的自适应+压缩的样式。这种不被支持

**Comment by biezhihua** [comment]
[template_text_fitcontent_two_text_shrink.zip](https://github.com/alibaba/GaiaX/files/10002666/template_text_fitcontent_two_text_shrink.zip)

**Comment by biezhihua** [comment]
https://wow.techbrood.com/fiddle/33125
