### ISSUE TITLE
Android 实现CustomView的回调时data只有value参数，没有extend等其他参数

### ISSUE THREAD

**Issue by zylcold** [alibaba/GaiaX#274]
**描述这个问题**

安卓实现CustomView的回调时data只有value参数，没有extend等其他参数

**复现步骤**

可通过分步复现该问题：
1. 实现 CustomView
2. 在 onBindData 打印 data

**预期正确的结果**
包含 value 、extend等参数

**截图**
<img width="841" alt="wecom-temp-156617-0d6036b7e4a37759224aae15229b36dd" src="https://user-images.githubusercontent.com/7792014/202980060-83795498-3f3a-485d-89b4-4c9ab03cb25a.png">

<img width="844" alt="wecom-temp-97523-4130f7e23ff127ddd2f348e3389e39a1" src="https://user-images.githubusercontent.com/7792014/202980256-8d4fdf38-fc45-4b23-8c41-1acd99fc3f43.png">

**客户端 (请填写如下信息)  :**
 - 设备: Android
 - 系统: 
 - GaiaX SDK版本 0.2.9

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by biezhihua** [comment]
https://github.com/alibaba/GaiaX/pull/275
