### ISSUE TITLE
Studio：iOS 设置属性动画闪退，提示 expressionError: unexpected identifier 'prop' in expression 'prop'

### ISSUE THREAD

**Issue by zylcold** [alibaba/GaiaX#277]
**描述这个问题**
iOS 设置动画崩溃

**复现步骤**

可通过分步复现该问题：
1. 给一个view设置属性动画（prop动画）
2. 预览
3. 产生错误

**预期正确的结果**
正常展示动画效果

**截图**
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/7792014/203004549-c66a8b25-e6c1-47b9-81a8-02ea98f0600d.png">
<img width="868" alt="image" src="https://user-images.githubusercontent.com/7792014/203004851-9ec49f2e-e47c-449d-bdf8-5c07c1cebbcd.png">

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 0.2.9
 - GaiaX 模板文件和模板数据

**崩溃日志**
expressionError: unexpected identifier 'prop' in expression 'prop'

**附加信息**

[jy_main_live_scroll_item.gaiax.zip](https://github.com/alibaba/GaiaX/files/10054811/jy_main_live_scroll_item.gaiax.zip)

**Comment by zylcold** [comment]
GaiaX Stdio 版本  0.1.21 (0.1.21)

**Comment by biezhihua** [comment]
客户端问题

**Comment by biezhihua** [comment]
表达式只是的范围。

**Comment by biezhihua** [comment]
修复内容：
 - 动画域value全部支持表达式，双端统一 @biezhihua 
 - 文档改动 @jingcheng1988 
修复时间：
 - 11月29~12月2

**Comment by biezhihua** [comment]
@zylcold 由于近期业务较忙，相关问题跟进较慢，请耐心等待。

**Comment by biezhihua** [comment]
https://github.com/alibaba/GaiaX/pull/303
