### ISSUE TITLE
css布局右边距展示异常

### ISSUE THREAD

**Issue by tonight1988** [alibaba/GaiaX#282]
**Describe the bug**
 
```
#video-card {
  width: 100%;
  height: 200px;
  background-color: #ffff00;
}

#box-view {
  height: 100px;
  width: 100%;
  background-color: #e44545;
  margin-top: 10px;
  margin-bottom: 10px;
  margin-left: 30px;
  margin-right: 30px;
}
```

**Expected behavior**

预期展示的红色控件右边应该留有间距.

**Screenshots**
<img width="527" alt="image" src="https://user-images.githubusercontent.com/13066816/203773325-541c1d4c-e871-4138-ba6d-e2f29ca05e6e.png">

**Phone (please complete the following information)  :**
 - Device: [e.g. iPhone 7]
 - OS: [e.g. iOS 15.0.1]
 - GaiaX SDK Version [e.g. 0.2.8]
 - GaiaX Template File and Template data

**Comment by jingcheng1988** [comment]
首先说一下，这个是一个正常的FlexBox布局规则和效果，双端预览效果肯定也是一致的
如果要达到你issue说的布局效果，可以采用下面两种方式：
1.video-card 设置左右padding为30px，box-view宽度设置为100%
2. video-card保持不变，box-view的宽度去掉，设置flex-grow为1
