### ISSUE TITLE
iOS表达式解析精度异常

### ISSUE THREAD

**Issue by tonight1988** [alibaba/GaiaX#290]
**Describe the bug**

表达式解析JSON数据后,数据出现精度异常,与预期不一致

![image](https://user-images.githubusercontent.com/13066816/205548438-3a597971-acc6-41ad-93b6-f263a1e202d4.png)

**Phone (please complete the following information)  :**
 - Device: [e.g. iPhoneXs]
 - OS: [e.g. iOS15.5]
 - GaiaX SDK Version [e.g. 0.2.8]
 - GaiaX Template File and Template data

**Additional context**

复现模板,绑定的Mock数组是文件夹内的test.json
[test 2.zip](https://github.com/alibaba/GaiaX/files/10150596/test.2.zip)

**Comment by MXPDS6688** [comment]
已修复 #293
