### ISSUE TITLE
使用Demo 扫码后，绑定的数据无法显示

### ISSUE THREAD

**Issue by Skandinaviske** [alibaba/GaiaX#291]
**描述这个问题**

使用GaiaXAndroidDemo app 在Android手机上扫码Gaiax Studio上绘制的图案后，可出现相应的图案，但是无法显示绑定的文字以及绑定的图片（在Studio上输入过了相应的URL）

**预期正确的结果**

应该显示出绑定的文字与图片信息

**截图**

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**
 - 设备: OPPO FInd X3
 - 系统: ColorOS 13
 - GaiaX SDK版本 使用的Main分支上的Demo
 - Gaia Studio版本 0.1.8
 - GaiaX 模板文件和模板数据

**崩溃日志**
[log.zip](https://github.com/alibaba/GaiaX/files/10151422/log.zip)

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by Skandinaviske** [comment]
[a.json.zip](https://github.com/alibaba/GaiaX/files/10151831/a.json.zip)
使用GAIAX STudio生成的json文件

**Comment by liyafly** [comment]
iOS 同样不显示文本。
```
long GXAnalyze::check(string s, vector<GXATSNode> array, void *p_analyze, void *source,
                      string expression)
```
方法中捕捉错误
```
2022-12-05 16:18:42.755733+0800 GaiaXiOSDemo[550:69131] 错误信息：expressionError: unexpected identifier 'helloword' in expression 'helloword'
```
<img width="1612" alt="截屏2022-12-05 16 23 00" src="https://user-images.githubusercontent.com/26201271/205588865-9f0cbd68-d1b9-4d27-b67c-05d72e5e1406.png">

**Comment by MXPDS6688** [comment]
studio版本问题，已修复
