### ISSUE TITLE
基础视图扩展

### ISSUE THREAD

**Issue by HelooM** [alibaba/GaiaX#299]
请问除了内置的的view、image、text、scroll这些基础组件外，支持扩展吗？比如加一个按钮类型？需要怎么做呢？

**Comment by biezhihua** [comment]
> 请问除了内置的的view、image、text、scroll这些基础组件外，支持扩展吗？比如加一个按钮类型？需要怎么做呢？

@HelooM 目前不支持扩展基础组件。

基础组件的新增需要GaiaStudio和GaiaXSDK一起配合才能工作，这块会涉及到不少工作量。
