### ISSUE TITLE
请教一下GaiaX的布局过程是异步还是同步的？

### ISSUE THREAD

**Issue by tbruceyu** [alibaba/GaiaX#300]
看到Gaia是利用的libstretch做的布局引擎，能否支持异步布局呢？

**Comment by biezhihua** [comment]
> 看到Gaia是利用的libstretch做的布局引擎，能否支持异步布局呢？

@tbruceyu 可以支持异步布局。这块我们会在明年1~2月份开源。

**Comment by tbruceyu** [comment]
期待啊！
