### ISSUE TITLE
埋点解析中会将整形解析为浮点型，long转成String还会变成科学计数的格式

### ISSUE THREAD

**Issue by jiyuegongzi** [alibaba/GaiaX#309]
![image](https://user-images.githubusercontent.com/11285176/208579904-58825b06-4a2b-432b-bb17-709bedd372ed.png)

**Comment by biezhihua** [comment]
@jiyuegongzi 请提供可用于复现的demo，协助我们更快更准确解决问题

**Comment by jiyuegongzi** [comment]
你们的demo就能复现， 我使用你们demo复现的

**Comment by MXPDS6688** [comment]
浮点数（float,double）整数部分达到8位及以上，会以科学计数法显示。
原生是默认这么处理的，如果需要上报数据时显示完整的浮点数，可以通过转换为BigDecimal然后再上报数据。
