### ISSUE TITLE
Android真机打开实时预览功能Native闪退

### ISSUE THREAD

**Issue by gaoganlsz** [alibaba/GaiaX#315]
**错误描述**
实时预览功能Native崩溃
**步骤**
1.打开编辑工具,创建只有一张图片模板
2.打开源码[tag:0.3.0]的app demo工程
3.Demo中[实时预览]扫码, 编辑工具提示[链接成功]
4.添加一个简单的图片, 修改图片宽度,多次修改(2-5次)
5.Native崩溃
**错误描述详细信息**
参考Xcrash的错误日志:
1.动态修改图片宽高的闪退
[tombstone_00001672739616413035_unknown__com.alibaba.gaiax.demo.native.txt](https://github.com/alibaba/GaiaX/files/10335697/tombstone_00001672739616413035_unknown__com.alibaba.gaiax.demo.native.txt)
2.动态修改TextView文本的闪退
[tombstone_00001672736210925398_unknown__com.alibaba.gaiax.demo.native.txt](https://github.com/alibaba/GaiaX/files/10335703/tombstone_00001672736210925398_unknown__com.alibaba.gaiax.demo.native.txt)

**复现的模板**
只有一张图片
[tangdou_main.zip](https://github.com/alibaba/GaiaX/files/10336172/tangdou_main.zip)

**Comment by biezhihua** [comment]
01-03 16:57:25.193  3267  3267 E [GaiaX] : unknown identifier: .
01-03 16:57:25.193  3267  3267 E [GaiaX] : unknown identifier: .
01-03 16:57:25.193  3267  3267 E [GaiaX] : expressionError: unexpected identifier 'https' in expression 'https://via.placeholder.com/100'

**Comment by biezhihua** [comment]
"index.data":"{\"tangdou_image\":{\"value\":\"https://via.placeholder.com/100\"}

**Comment by biezhihua** [comment]
@gaoganlsz 经过排查，猜测是你使用index.data而不是index.databining来设置数据绑定的。请使用index.databinding来设置数据绑定关系。
