### ISSUE TITLE
Android使用scroll模版创建列表，item展示不全

### ISSUE THREAD

**Issue by pj0579** [alibaba/GaiaX#316]
**描述这个问题**

Android使用scroll模版创建列表，item的模版没有设置宽高，尺寸自适应的，列表第一条文案一行，可以正常展示，第二条和第三条内容展示不全

**复现步骤**

使用模板展示数据

**预期正确的结果**
各个item完全展示

**截图**
<img width="460" alt="lQLPJxB4Q_0sZezNBSrNA5iwJ7xhmM2MNyADr2towUD9AA_920_1322" src="https://user-images.githubusercontent.com/20592579/210344373-ccca0aa7-0f5a-45a4-9eb5-750e7d47077f.png">

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [0.2.9]
 - Gaia Studio版本 [0.2.9]
 - GaiaX 模板文件和模板数据
[模板.zip](https://github.com/alibaba/GaiaX/files/10336034/default.zip)
[mock.json.zip](https://github.com/alibaba/GaiaX/files/10336107/mock.json.zip)

**崩溃日志**
在这里添加崩溃日志

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by biezhihua** [comment]
@pj0579 明天内会给出反馈

**Comment by biezhihua** [comment]
https://github.com/alibaba/GaiaX/pull/318

**Comment by biezhihua** [comment]
@pj0579 目前Android端问题已经修复，但是还需要校验双端逻辑是否一致，目前还无法合并。

**Comment by biezhihua** [comment]
[jy_home_question_style3_grid_item.zip](https://github.com/alibaba/GaiaX/files/10343978/jy_home_question_style3_grid_item.zip)

@pj0579 你的坑位模板实现的有问题，我帮你改了一下。

**Comment by pj0579** [comment]
@biezhihua  好的 我看下👌
