### ISSUE TITLE
Android 注册扩展数据源报错

### ISSUE THREAD

**Issue by pj0579** [alibaba/GaiaX#321]
请清晰和简明的描述这个问题。

初始化GaiaX代码如下：
`GXTemplateEngine.instance.init(context)
GXRegisterCenter.instance.registerExtensionTemplateSource(GXLocalTemplate(context), 1001)`
使用如上代码初始化导致 java.lang.NullPointerException 和 java.util.ConcurrentModificationException

可通过分步复现该问题：
初始化正常

请清晰和简明的描述你预期正确的结果。

初始化正常
如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**
 - 设备: [Android]
 - 系统: [Android9～12]
 - GaiaX SDK版本 [0.3.0]
 - Gaia Studio版本 [0.3.2]
 - GaiaX 模板文件和模板数据

**崩溃日志**
线上bugly上报的bug如下：
<img width="669" alt="WechatIMG156" src="https://user-images.githubusercontent.com/20592579/211453272-2d22125e-946e-4cc2-b8b5-cd7c7faed923.png">
<img width="635" alt="image" src="https://user-images.githubusercontent.com/20592579/211453434-ec2db97b-19a1-434b-b12c-7980d6a5f936.png">
<img width="657" alt="image" src="https://user-images.githubusercontent.com/20592579/211453522-d751baed-cd87-4abf-903c-790fac18dbd4.png">
<img width="692" alt="image" src="https://user-images.githubusercontent.com/20592579/211453645-c64bccf5-2de3-4477-b32e-7d71cf0b0d71.png">
<img width="745" alt="image" src="https://user-images.githubusercontent.com/20592579/211453704-edbb956a-2091-48d0-a15b-7bc223c7d9e4.png">
<img width="647" alt="image" src="https://user-images.githubusercontent.com/20592579/211453868-9614d693-03a8-4155-845a-69afe613b993.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/20592579/211453940-03454d4a-358b-4a94-89c0-383702ce983b.png">

**Comment by biezhihua** [comment]
@pj0579 扩展数据源一般只会在app启动的时候注册一次，并且不是线程安全的，看你这个日志，是不是在多个地方同时注册数据源了。 

这块在业务层面是不是有问题？

**Comment by biezhihua** [comment]
@pj0579 这块如果要从SDK侧修复，只能是增加线程安全的处理。但是app内多个地方重复注册，的确不是很常见。
