### ISSUE TITLE
为什么内置的View都采取反射创建？这样会影响性能

### ISSUE THREAD

**Issue by ruanchaohouzi** [alibaba/GaiaX#339]
**描述这个问题**

为什么下面这些内置的View都采取反射创建，而不是直接new，这样页面层级比较多，是不是很影响性能？

viewSupport[GXViewKey.VIEW_TYPE_GAIA_TEMPLATE] = GXView::class.java
        viewSupport[GXViewKey.VIEW_TYPE_VIEW] = GXView::class.java
        viewSupport[GXViewKey.VIEW_TYPE_TEXT] = GXText::class.java
        viewSupport[GXViewKey.VIEW_TYPE_RICH_TEXT] = GXRichText::class.java
        viewSupport[GXViewKey.VIEW_TYPE_IMAGE] = GXImageView::class.java
        viewSupport[GXViewKey.VIEW_TYPE_CONTAINER_SCROLL] = GXScrollView::class.java
        viewSupport[GXViewKey.VIEW_TYPE_CONTAINER_GRID] = GXGridView::class.java
        viewSupport[GXViewKey.VIEW_TYPE_ICON_FONT] = GXIconFont::class.java
        // viewSupport[GXViewKey.VIEW_TYPE_LOTTIE] = GXLottie::class.java
        viewSupport[GXViewKey.VIEW_TYPE_SHADOW_LAYOUT] = GXShadowLayout::class.java
        viewSupport[GXViewKey.VIEW_TYPE_CONTAINER_SLIDER] = GXSliderView::class.java
        viewSupport[GXViewKey.VIEW_TYPE_CONTAINER_BANNER] = GXBannerView::class.java
        viewSupport[GXViewKey.VIEW_TYPE_PROGRESS] = GXProgressView::class.java
        viewSupport[GXViewKey.VIEW_TYPE_SCROLL_CONTAINER] = GXScrollContainerView::class.java

**Comment by biezhihua** [comment]
@ruanchaohouzi  之前是为了方便外部注册替换。 

其实这块也可以改成new的方式进行类的生成。

**Comment by biezhihua** [comment]
@ruanchaohouzi 你这个问题很不错。 你这边有兴趣一起做这个改动么？ 我可以发起一个新的代码改动。

**Comment by biezhihua** [comment]
https://github.com/alibaba/GaiaX/pull/341

**Comment by biezhihua** [comment]
@ruanchaohouzi 感谢你的建议，该问题已经在 https://github.com/alibaba/GaiaX/pull/341 中被修复，你可以在main分支上拉取。
