### ISSUE TITLE
DEBUG代码提交

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#351]
**描述这个问题**

iOS DEBUG代码，在源码引入的时候导致DEBUG阶段进入了debug代码

**复现步骤**

1. 源码依赖
2. debug mode运行

**预期正确的结果**

不进入debug代码

**截图**

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [e.g. 0.3.0]
 - Gaia Studio版本 [e.g. 0.3.11]
 - GaiaX 模板文件和模板数据

**崩溃日志**

**附加信息**
```objc
#if DEBUG == 1
    NSString *bizBundlePath = nil;
    if ([bundleName isEqualToString:@"GaiaXiOSTests.bundle"]) {
        NSBundle *bundle = [NSBundle bundleForClass:NSClassFromString(@"GaiaXiOSTests")];
        bizBundlePath = [bundle pathForResource:bundleName ofType:nil];

    } else {
        bizBundlePath = [[NSBundle mainBundle] pathForResource:bundleName ofType:nil];
    }
#else
    NSString *bizBundlePath = [[NSBundle mainBundle] pathForResource:bundleName ofType:nil];
#endif
```

**Comment by jingcheng1988** [comment]
此处的代码逻辑值只是为了在Debug模式下兼容单元测试，并不会影响到业务的实际使用，实际效果和Release是保持一致的
