### ISSUE TITLE
text组件设置fit-content后，并且宽度被动态修改后存在宽度异常

### ISSUE THREAD

**Issue by ruanchaohouzi** [alibaba/GaiaX#353]
**描述这个问题**

text组件设置fit-content后，并且宽度被动态修改后存在宽度异常，宽度还是之前CSS中的宽度，并不是extend动态修改后的宽度？

#text_demo {
    align-self: flex-start;
    width: 40px;
    height: auto;
    fit-content: true;
}

"text_demo": {
      "extend": {
        "width": "'200px'",
      }
}

如上所示，实际渲染出来的宽度还是对应的40px，预期结果应该是200px

看了GXFitContentUtils代码，存在问题

![image](https://user-images.githubusercontent.com/9404322/223301678-60dc3eb0-758e-4cb1-93f6-69d5e111e006.png)

nodeWidth = nodeLayout.width是存在问题的，应该取改动后的宽度，我看对高度做了处理，是不是没有对宽度做处理？？

**Comment by biezhihua** [comment]
@ruanchaohouzi 请贴一下完整的模板和mock数据。

**Comment by ruanchaohouzi** [comment]
[test.zip](https://github.com/alibaba/GaiaX/files/10920102/test.zip)
文字的宽度实际在extend中修改成了200px    但是实际预览无效，还是css中的宽度20px    由于fit-content里面有问题

**Comment by ruanchaohouzi** [comment]
> @ruanchaohouzi 请贴一下完整的模板和mock数据。

模板数据如下test.zip文件夹

**Comment by biezhihua** [comment]
> > @ruanchaohouzi 请贴一下完整的模板和mock数据。
> 
> 模板数据如下test.zip文件夹

OK。 我明天看下。

**Comment by biezhihua** [comment]
@ruanchaohouzi 

```
{ "data": { "title": { "extend": { "width": "'200px'" } } } }
```

我看你没有给title绑定数据呀？此时fitcontent的逻辑应该是不生效的。

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/223946637-bc33696a-d2ed-4316-a07d-c7791c17c6f1.png)

**Comment by ruanchaohouzi** [comment]
[testNew.zip](https://github.com/alibaba/GaiaX/files/10928977/testNew.zip)

我更新了下模板，直接绑定了数据，宽度还是不对的  @biezhihua

**Comment by biezhihua** [comment]
> [testNew.zip](https://github.com/alibaba/GaiaX/files/10928977/testNew.zip)
> 
> 我更新了下模板，直接绑定了数据，宽度还是不对的 @biezhihua

我明天看下

**Comment by biezhihua** [comment]
@ruanchaohouzi 的确有BUG，我需要修复一下。

**Comment by biezhihua** [comment]
https://github.com/alibaba/GaiaX/pull/362
