### ISSUE TITLE
【咨询】小程序支持吗？有使用Gaiax应用到小程序实现动态化渲染的吗？

### ISSUE THREAD

**Issue by Jay-Ivy** [alibaba/GaiaX#354]
**描述这个问题**

求助，咨询，有大佬使用Gaiax做动态化应用到微信或支付宝小程序中的吗？
若需要使用，是不是需要使用Ｔａｒｏ来进行小程序的重构才能应用？

**附加信息**
先谢过各位大佬，帮忙回复一下！

**Comment by biezhihua** [comment]
目前GaiaXTaro还未正式发布
