### ISSUE TITLE
【@gaiax/taro】GaiaXTaro\packages\gaiax-taro-demo 项目依赖包@gaiax/taro无法找到，npm官方资源库也没有

### ISSUE THREAD

**Issue by Jay-Ivy** [alibaba/GaiaX#355]
**描述这个问题**

【@gaiax/taro】GaiaXTaro\packages\gaiax-taro-demo 项目依赖包@gaiax/taro无法找到，npm官方资源库也没有

**复现步骤**

下载github代码，按步骤执行：yarn bootstrap、yarn build、cd packages/gaiax-taro-demo、yarn dev:weapp

**预期正确的结果**

编译成功

**截图**

编译失败
![image](https://user-images.githubusercontent.com/15058734/223401296-aedbf225-a9e5-4835-8638-7b2ea2e591c0.png)

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [e.g. 0.1.0]
 - Gaia Studio版本 [e.g. 0.1.0]
 - GaiaX 模板文件和模板数据

**崩溃日志**
在这里添加崩溃日志

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by biezhihua** [comment]
目前GaiaXTaro还未正式发布，还处于开发阶段。
