### ISSUE TITLE
HTML String支持

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#356]
**描述这个问题**

希望能支持html string 的渲染

**Comment by biezhihua** [comment]
@JohnTsaii 你是希望在原有text上进行渲染，还是新开视图类型进行渲染？ 例如：htmlText这种。

**Comment by JohnTsaii** [comment]
感谢回复，最好的话，希望能直接在text上渲染。这样我们对于富文本+html统一使用一个控件就好了 @biezhihua

**Comment by JohnTsaii** [comment]
@biezhihua 我尝试了一下，Android IconFont是支持html String的 iOS的IconFont不支持html String,请问是什么原因呢

**Comment by biezhihua** [comment]
> @biezhihua 我尝试了一下，Android IconFont是支持html String的 iOS的IconFont不支持html String,请问是什么原因呢

双端对解析iconfont字符逻辑有所不同，其主要目的不是为了解析HTML来使用的。

**Comment by JohnTsaii** [comment]
> > @biezhihua 我尝试了一下，Android IconFont是支持html String的 iOS的IconFont不支持html String,请问是什么原因呢
> 
> 双端对解析iconfont字符逻辑有所不同，其主要目的不是为了解析HTML来使用的。

嗯嗯 好的
