### ISSUE TITLE
【咨询】想问下 Taro 版本大概什么时候会正式发布？

### ISSUE THREAD

**Issue by CyberFei** [alibaba/GaiaX#359]
想问下 Taro 版本大概什么时候会正式发布？

**Comment by biezhihua** [comment]
@CyberFei 目前时间未确定，预计下周可以给出一个回复。

**Comment by biezhihua** [comment]
> @CyberFei 目前时间未确定，预计下周可以给出一个回复。

正在计划中，时间待定。
