### ISSUE TITLE
【咨询】想请教下，image控件，能不能根据资源自适应宽高

### ISSUE THREAD

**Issue by zhangjin0725** [alibaba/GaiaX#360]
**描述这个问题**

一个image控件，想根据场景，展示不同的资源。资源高度不一样
当前image控件，不配置默认高度，渲染的高度是0
目前设置相同高度，通过修改缩放和剪切模式等条件，均不能实现我需求的效果。

**预期正确的结果**

根据我传入的资源，展示动态的宽高

**客户端 (请填写如下信息)  :**
 - 设备: [e.g. iPhone6]
 - 系统: [e.g. iOS8.1]
 - GaiaX SDK版本 [e.g. 0.1.0] ： 0.4.0
 - Gaia Studio版本 [e.g. 0.1.0]： 0.3.11
 - GaiaX 模板文件和模板数据

**附加信息**
在这里添加有关该问题的任何其他信息。

**Comment by biezhihua** [comment]
@zhangjin0725 在image控件的宽度或者高度，有一方确认的情况下，可以使用宽高比来根据不同的场景，动态计算出高度或者宽度。

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/224212263-f113b801-534d-4b9d-a168-2a2b9067a250.png)

**Comment by zhangjin0725** [comment]
两张资源的宽高比并不一致呢

**Comment by zhangjin0725** [comment]
我的场景，由于状态栏高度不一致，我两张资源的宽度一致的情况下，高度不一致

**Comment by biezhihua** [comment]
> 我的场景，由于状态栏高度不一致，我两张资源的宽度一致的情况下，高度不一致

目前image控件没有自适应的能力。

我的建议是根据状态栏状态，为image控件设置不同的高度，然后用较大的一张图在不同高度的image控件上进行展示，并且设置，让图片只显示底部。

mode-type:crop 
mode:bottom

**Comment by biezhihua** [comment]
![image](https://user-images.githubusercontent.com/6761107/224217484-d016b924-9793-4e60-809b-4b460be8f07e.png)
