### ISSUE TITLE
【咨询】您好，请问咱们有关于层级剪枝的相关优化吗？

### ISSUE THREAD

**Issue by lvzishen** [alibaba/GaiaX#361]
您好，我是一名Android开发，据我了解Yoga是可以做一些剪枝优化，请问咱们有这方面的逻辑吗？

**Comment by biezhihua** [comment]
@lvzishen 我们底层用的是stretch库来计算flexbox布局的，它对标的是yoga。

相对于yoga轻量了很多，具体是否有剪枝优化，我不是特别了解，你可以自行前往：https://github.com/vislyhq/stretch，这里看一下。

**Comment by lvzishen** [comment]
> @lvzishen 我们底层用的是stretch库来计算flexbox布局的，它对标的是yoga。
> 
> 相对于yoga轻量了很多，具体是否有剪枝优化，我不是特别了解，你可以自行前往：
> 
> https://github.com/vislyhq/stretch
> 
> 这里看一下。

谢谢回复，咱们目前DSL框架里是没有这种剪枝的自身逻辑处理的吧？基于stretch库的能力，然后咱们自己框架做的一些剪枝处理？
