### ISSUE TITLE
GaiaXiOS 属性动画参数设置问题

### ISSUE THREAD

**Issue by zhangbao-developer** [alibaba/GaiaX#373]
iOS 属性动画，设置延迟时间时，需要添加CACurrentMediaTime()，
下面为代码

        CAKeyframeAnimation *animation = [CAKeyframeAnimation animationWithKeyPath:model.keyPath];
        animation.fillMode = kCAFillModeForwards;
        animation.removedOnCompletion = NO;
        animation.delegate = self;
        animation.beginTime = CACurrentMediaTime() + model.delay;
        animation.duration = model.duration;
        animation.repeatCount = model.repeatCount;
        animation.autoreverses = model.autoReverse;
        [animation setValues:values];
        [animations addObject:animation];

另外，是否有表达式可以自定义属性动画？希望支持一下

**Comment by jingcheng1988** [comment]
目前的属性动画是支持设置延迟时间属性的，可以参考GXPropAnimationModel类中的delay属性
