### ISSUE TITLE
iOS unit test文件移除

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#384]
**描述这个问题**

iOS tests文件被打入pods，导致我工程的test case 执行结果失败

**复现步骤**

**预期正确的结果**

移除tests文件

**截图**

**客户端 (请填写如下信息)  :**
 - GaiaX SDK版本 [0.4.1]

**Comment by biezhihua** [comment]
@JohnTsaii 0.4.1版本是我发布的。 

我研究一下。

**Comment by biezhihua** [comment]
@JohnTsaii 不太会改，晚点在看

**Comment by biezhihua** [comment]
https://github.com/alibaba/GaiaX/pull/388
