### ISSUE TITLE
曝光埋点支持的问题

### ISSUE THREAD

**Issue by FanGuangcheng** [alibaba/GaiaX#389]
**描述这个问题**

如题，Android端使用了scroll组件，但是组件的item滑动的时候，没有曝光回调。

请问有考虑支持支持列表item自动曝光功能吗？

查看了之前关于埋点的issue，发现也不支持列表组件的曝光埋点功能：
https://github.com/alibaba/GaiaX/issues/176
https://github.com/alibaba/GaiaX/issues/166

**Comment by biezhihua** [comment]
@FanGuangcheng 

**解决方案：**

列表的曝光需要 `GXIEventListener.onScrollEvent(gxScroll: GXScroll)` 和 `GXITrackListener.onManualExposureTrackEvent(gxTrack: GXTrack)` 结合使用。

简单来说，GaiaX不会直接触发Scroll的Item坑位的回调。就像GaiaX需要业务方手动调用`onAppear`才能回调 `GXITrackListener.onManualExposureTrackEvent(gxTrack: GXTrack)` 一样。

GaiaX为业务准备了 `GXIEventListener.onScrollEvent(gxScroll: GXScroll)` 回调，用于监控scroll的滚动状态。当scroll从滚动状态变为静止状态时，业务方需要获取可见的坑位，然后手动调用坑位的`onAppear`才行。


**后续支持：**
scroll的自动曝光可以做到SDK中，这样能节省业务方不少麻烦。 但是由于内部原因，未来会考虑添加，但是时间不确定。

**Comment by biezhihua** [comment]
https://github.com/alibaba/GaiaX/pull/390

@FanGuangcheng 正好这会有空。写了一个自动触发scroll的坑位曝光回调的逻辑，你可以验证一下。如果没问题，我会合并一下。

**Comment by JohnTsaii** [comment]
iOS 也能顺便支持下吗 @biezhihua

**Comment by biezhihua** [comment]
@JohnTsaii iOS我不是很熟，要添加feature的话，可能要往后靠一靠了。

时间上不太确定。

**Comment by FanGuangcheng** [comment]
> #390
> 
> @FanGuangcheng 正好这会有空。写了一个自动触发scroll的坑位曝光回调的逻辑，你可以验证一下。如果没问题，我会合并一下。


好像还有点问题，我单步调试了下，发现最终是在onBindViewHolder的时候才会回调曝光事件接口，这个和产品理解的有点冲突。
比如，总共有10个item，屏幕内可以展示3个，滑动到最后一个的时候，再向前滑动一个，这时候会展示第7个，第7个item由不可见变为可见，应该触发曝光事件。但由于列表组件的复用逻辑，此时不会触发onBindViewHolder方法，因此不会SDK没有调用曝光埋点事件。

看来，我们自己业务方要自己写曝光逻辑，用你之前提供的思路：
列表的曝光需要 GXIEventListener.onScrollEvent(gxScroll: GXScroll) 和 GXITrackListener.onManualExposureTrackEvent(gxTrack: GXTrack) 结合使用。


最后，还是非常感谢你，百忙之中抽出时间帮我们解决问题~！！

**Comment by biezhihua** [comment]
@FanGuangcheng  

我的这个feature内部用的OnScrollListener做的状态监听，应该和坑位的onBindViewHolder是否触发没有关系的。 

当scroll从滑动变位不滑动，会获取屏幕内可见的item，然后触发事件回调的。 不过这个是我推测的情况。

这个我有空也自己验证一下。

**Comment by FanGuangcheng** [comment]
> 

我是在GXTemplateEngine.GXITrackListener的onTrackEvent里面监听的，发现不是每个item都能回调曝光。

如果你那边验证正常了，麻烦回复我一下，我更新SDK。
@biezhihua

**Comment by biezhihua** [comment]
https://github.com/alibaba/GaiaX/pull/390

这个实现的确有些问题，无法正确处理曝光的问题。

不过业务依旧可以使用上面的思路进行曝光的处理。

由于社区版本不考虑将这部分逻辑补齐，这个issue就直接关闭了。
