### ISSUE TITLE
iOS GXImageView webp动图 loopcount无效

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#392]
**描述这个问题**

iOS gaiax webp动图loopcount属性在GXImageView里无效，动图会一直循环播放。

**复现步骤**

1. 找一张循环一次的webp动图
2. 加载就会看到动图一直循环播放

**预期正确的结果**
可以根据图片里的loopcount信息来确认播放次数

**客户端 (请填写如下信息)  :**
 - 设备: [iPhone 13 Pro]
 - 系统: [iOS 16.1.2]
 - GaiaX SDK版本 [0.4.1]

**Comment by JohnTsaii** [comment]
@biezhihua 试了一下Android也有这个问题

**Comment by biezhihua** [comment]
> @biezhihua 试了一下Android也有这个问题

因为优酷的图片加载组件是自己写的所以可能没这些问题。 

如果需要修复，你这边可以提供一些场景，或者PR。

**Comment by JohnTsaii** [comment]
Android我们自定义了图片加载实现解决了这个问题

**Comment by biezhihua** [comment]
> Android我们自定义了图片加载实现解决了这个问题

嗯。 iOS没有提供扩展能力。 这个能力我同事正在开发。
