### ISSUE TITLE
支持根据图片size自动计算ImageNode的宽高

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#398]
**描述这个问题**

目前不支持根据图片size自动计算ImageNode的宽高

**预期正确的结果**

支持根据图片size自动计算ImageNode的宽高

**客户端 (请填写如下信息)  :**
 - 设备: [iPhone6]
 - 系统: [iOS 13]
 - GaiaX SDK版本 [0.4.1]
 - Gaia Studio版本 [0.3.11]

**Comment by biezhihua** [comment]
@JohnTsaii 

目前GaiaX的整体都按都是偏向静态的。 也就是说，它要求开发者提前就能确定模板中各元素的宽高。 

例如：
- 固定宽度、高度；
- 固定宽度，自适应高度；
- 固定高度，自适应宽度；
- 固定宽度，按比例求高度；
- 固定高度，按比例求宽度。

总体要求至少知道一条边的宽度，才能方便flexbox计算。

你所说的的根据图片自己的尺寸信息（例如：图片是100*100）的，来为image组件自动设置宽高信息，这就要求GaiaX预先加载图片，并获取其宽高，然后再指定image组件的宽高，再去进行flexbox的计算。这个流程很类似与文字自适应的计算逻辑（fitcontent）。

这个流程与现有流程差异较大，改造起来工作量也较大，且使用频率并非很高。

在优酷的设计场景中，为了适配多种屏幕，多种场景，往往会采取按比例的形式，为组件设置宽度，然后让图片自己去填满image组件。

**Comment by JohnTsaii** [comment]
@biezhihua 固定高度，自适应宽度； 这个要如何实现呢

**Comment by JohnTsaii** [comment]
1. image 组件  高度固定，宽度是随机的，宽高比是不确定的（我们遇到的就是这种情况）
2. view 组件 这个就是自适应吧

**Comment by JohnTsaii** [comment]
好的。感谢回复
