### ISSUE TITLE
ios pod crash, 有计划修复吗?

### ISSUE THREAD

**Issue by amjunliang** [alibaba/GaiaX#4]
1. 新建工程 , 
2.   pod 'GaiaXiOS'
3. 更新pod
4. 打开项目真机运行 崩溃报以下错误
```
dyld: Library not loaded: @rpath/XCTest.framework/XCTest
  Referenced from: /private/var/containers/Bundle/Application/7D0527AC-DAF8-4655-BE83-0F45977564A3/TestGaiaX.app/TestGaiaX
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib
```

查了下, 是因为 
https://github.com/CocoaPods/Specs/blob/019a3d1b3894515bd6057e56b706309338e95272/Specs/8/e/a/GaiaXiOS/0.1.0/GaiaXiOS.podspec.json 这个配置,  "frameworks": "XCTest"  

XCTest不能链接到主target

**Comment by jingcheng1988** [comment]
在项目的Target ->  Buildi Setting -> Other Link Flags   添加配置项： -weak_framework   "XCTest"

**Comment by biezhihua** [comment]
> 在项目的Target -> Buildi Setting -> Other Link Flags 添加配置项： -weak_framework "XCTest"
> 
> <img alt="截屏2022-04-12 19 35 55" width="1432" src="https://user-images.githubusercontent.com/4187391/162951797-7ce05c23-3de4-47d9-bd21-bdfb2216a513.png">

@amjunliang

**Comment by amjunliang** [comment]
这个问题的修复是按照 [README.md](https://github.com/alibaba/GaiaX#readme)配置, 还是后续会更新[podspec.json](https://github.com/CocoaPods/Specs/blob/019a3d1b3894515bd6057e56b706309338e95272/Specs/8/e/a/GaiaXiOS/0.1.0/GaiaXiOS.podspec.json)呢? weak_framework也可以设置在podspec里面

**Comment by amjunliang** [comment]
> 可以先在项目的Target -> Buildi Setting -> Other Link Flags 添加/修改配置项为： -weak_framework "XCTest" <img alt="截屏2022-04-12 19 35 55" width="1432" src="https://user-images.githubusercontent.com/4187391/162951797-7ce05c23-3de4-47d9-bd21-bdfb2216a513.png">

如果客户端配置的话, 这个issue就可以关了

**Comment by jingcheng1988** [comment]
> 

后续我们会将weak_framework的设置更新到podspec中，感谢您的反馈
