### ISSUE TITLE
高度为啥不支持小数

### ISSUE THREAD

**Issue by zhnnnnn** [alibaba/GaiaX#401]
<img width="627" alt="image" src="https://github.com/alibaba/GaiaX/assets/11436094/5d7dfe6a-8da2-4eeb-9821-0685cd6a2459">

代码里只写死支持了0.5的情况

**Comment by biezhihua** [comment]
@zhnnnnn 好像是底层库计算有些问题，做的兼容处理。

**Comment by jingcheng1988** [comment]
为了提升渲染性能，实现像素对齐，底层库计算之后会做取整处理
