### ISSUE TITLE
JS 生命周期

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#406]
**描述这个问题**

Component({
    state: {},
    onShow: function() {
    },
    onReady: function() {
    },
    onHide: function() {},
    onReuse: function() {},
    onDestroy: function() {}
});

关于生命周期有明确的定义吗（分别是什么时候发生的）

**Comment by biezhihua** [comment]
@JohnTsaii 双端的JS能力都还没有正式发布，所以我们对JS的支持可能没有这么及时。

**Comment by JohnTsaii** [comment]
嗯，好的，最近我们用到了JS能力，这块可能咨询的会比较多，还是到discussions讨论吧
