### ISSUE TITLE
lottie动画配置后无法使用，demo直接crash

### ISSUE THREAD

**Issue by lohas2022** [alibaba/GaiaX#415]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Phone (please complete the following information)  :**
 - GaiaX SDK Version [e.g. 0.1.0]
 - GaiaX Template File and Template data

**Additional context**

**Comment by JohnTsaii** [comment]
@lohas2022 有具体的demo和复现步骤么，iOS lottie的动画是需要自己实现动画协议才能用的
