### ISSUE TITLE
二进制文件是如何生成？

### ISSUE THREAD

**Issue by fengning0901** [alibaba/GaiaX#419]
请教下GaiaX Studio中，二进制文件是如何压缩生成的？希望学习一下

**Comment by biezhihua** [comment]
@fengning0901 可以参考这里的解析逻辑：https://github.com/alibaba/GaiaX/pull/413/files#diff-e2cf2f8db989fbfb5ad96635c0b3dc615ed69f284b39deeb6350bd7610c1fb01
