### ISSUE TITLE
GaiaX Studio数据事件绑定页面无法关闭

### ISSUE THREAD

**Issue by tonight1988** [alibaba/GaiaX#421]
**描述这个问题**

GaiaX Studio在进入数据和事件绑定操作界面,界面无法关闭。

**复现步骤**

可通过分步复现该问题：
1. GaiaX Studio 
2. 数据和事件绑定 -> 点击编辑
3. 数据编辑页面关闭按钮点击无反应,GaiaX Studio无法进行后续功能使用

**预期正确的结果**

数据编辑页面关闭按钮点击后,编辑页面消失。

**截图**
![QQ20230724-113329](https://github.com/alibaba/GaiaX/assets/13066816/b6c339ac-30f5-4257-bac5-a3d835518526)

**客户端 (请填写如下信息)  :**
 - 设备: [MacBook Pro 2019]
 - 系统: [macOS Ventura 13.3.1]
 - Gaia Studio版本 [0.3.18]

**Comment by tonight1988** [comment]
@ronghui1219

**Comment by JohnTsaii** [comment]
我也遇到了类似问题，要点击左下角一点才行，这个体验非常不好。

**Comment by biezhihua** [comment]
@JohnTsaii @tonight1988 已经将该问题反馈给了 GaiaStudio负责同学。
