### ISSUE TITLE
Gaia Studio 导入导出时会剥离常量字符串的单引号

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#422]
**描述这个问题**

Gaia Studio 导入导出时会剥离常量字符串的单引号，导致加载模板的时候解析异常

**复现步骤**

将模板导入到gaia studio,其中databinding里的数据
"value": "'testURL'" 会变成 "value": "testURL" 少了单引号，其他的字符串都是有这种情况 比如 "'tap'" -> "tap"

**预期正确的结果**

请清晰和简明的描述你预期正确的结果。

**截图**

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**
 - Gaia Studio版本 [0.3.18]
**附加信息**
[mind_item_temp.zip](https://github.com/alibaba/GaiaX/files/12169224/mind_item_temp.zip)

**Comment by biezhihua** [comment]
@MXPDS6688 负责跟进。

**Comment by biezhihua** [comment]
已修复
