### ISSUE TITLE
框架JS能力什么时候开源呀？有计划开源吗？

### ISSUE THREAD

**Issue by 815065046** [alibaba/GaiaX#425]
**描述这个问题**
框架JS能力什么时候开源呀？有计划开源吗？

请清晰和简明的描述这个问题。
框架JS能力什么时候开源呀？有计划开源吗？

**Comment by biezhihua** [comment]
@815065046 

由于近期人力比较紧张。

目前JS开源计划被搁置了。

目前还没有明确的时间重启。
