### ISSUE TITLE
了解了下这个框架，相比于其它动态化框架其核心亮点应该是高性能了，想了解下这块有做过与主流框架的性能对比吗？另外想了解下框架与业务的结合情况，目前框架能够支撑优酷的核心业务迭代吗？

### ISSUE THREAD

**Issue by 815065046** [alibaba/GaiaX#428]
**描述这个问题**
了解了下这个框架，相比于其它动态化框架其核心亮点应该是高性能了，想了解下这块有做过与主流框架的性能对比吗？另外想了解下框架与业务的结合情况，目前框架能够支撑优酷的核心业务迭代吗？

请清晰和简明的描述这个问题。
了解了下这个框架，相比于其它动态化框架其核心亮点应该是高性能了，想了解下这块有做过与主流框架的性能对比吗？另外想了解下框架与业务的结合情况，目前框架能够支撑优酷的核心业务迭代吗？

**Comment by qiqiangqq** [comment]
目前GaiaX跨端渲染引擎在阿里文娱板块已经全面落地，日均渲染PV过亿次，所有使用了GaiaX的页面，冷启动耗时及滑动帧率都做过严格的测试，均符合上线要求。开源项目建设的初衷是在文娱板块已经有了很好的验证，技术团队希望可以把项目推送到开源社区，让更多的爱好者受益。
跨端方案，行业内是非常多的，什么粒度的都有。 Flutter、Weex、RN、Yoga==，我们跟Yoga方案做过一些横向对比，性能可以跟Yoga持平。 与其他方案的对比，没有大规模的客观数据对比，所以没有这方面的结论。 但作为定位于局部动态化的技术方案来说，性能不是问题。
另外，GaiaX项目的优势是配套体系， 文娱内我们定位的是设计研发一体化， 开源项目中我们也附带了GaiaStudio搭建工具。
