### ISSUE TITLE
Android纵向滑动列表无法展示

### ISSUE THREAD

**Issue by liuhong-coder** [alibaba/GaiaX#432]
**描述这个问题**

在测试GaiaXAndroidDemo里的模版数据时，使用模版gx-content-uper，data为uper.json，把子模版gx-content-uper-scoll的json文件中的direction改为vertical时，列表无法展示。设置gx-content-uper-scroll为固定高度时，列表可以展示，但是，我需要让这个列表自动充满频幕剩余空间，不能设置高度，请问有什么方法可以解决。

**预期正确的结果**

纵向列表可以自动充满频幕剩余空间。

**客户端 (请填写如下信息)  :**
 - 设备: [Android]
 - GaiaX 模板文件和模板数据

**Comment by biezhihua** [comment]
scroll不支持竖向的。 

gaiax主要是面向组件级别能力。
