### ISSUE TITLE
iOS js setData 导致动画重新被执行一遍

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#434]
**描述这个问题**

使用js更新元素数据的数据出了setData之外还有其他方式吗？发现用js setData的方式来刷新UI会导致动画被重新执行一遍

**复现步骤**
在有动画模板的setData必现
**预期正确的结果**

只更新对应UI数据

**截图**

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**
 - GaiaX SDK版本 [ios_js_develop分支]

**Comment by biezhihua** [comment]
@JohnTsaii 

https://youku-gaiax.github.io/GaiaXSDK/style-animation/lottie-animation.html#ios%E5%AE%9E%E7%8E%B0


要想控制动画是否执行，需要利用trigger+state才行。

**Comment by JohnTsaii** [comment]
上面的方法是可行的
