### ISSUE TITLE
Gaia Studio 开源

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#440]
**描述这个问题**

有计划开源Gaia Studio吗？我们目前是在GaiaX上扩展了一些自定义的业务实现，由于Gaia Studio的限制导致一些新的功能无法在Gaia Studio 上直接表现。

**客户端 (请填写如下信息)  :**
 - Gaia Studio版本 [0.3.18]

**Comment by biezhihua** [comment]
会提供插件化能力，让大家可以自己闭环开发。
已经在开发中了
