### ISSUE TITLE
JS的setData逻辑在嵌套模板情况下有问题

### ISSUE THREAD

**Issue by zhnnnnn** [alibaba/GaiaX#442]
节点的orignalData的赋值只是在最外层的模板上做了，嵌套模板的情况下。js获取根节点可能拿到的不是最外层。也就拿不到orignalData。最终会导致刷新失败

**Comment by JohnTsaii** [comment]
可以通过模板间通讯的方法，将事件透传到主模板，主模板刷新
https://www.yuque.com/youku-gaia/nex85n/gzqphslaggxcb934

**Comment by biezhihua** [comment]
@zhnnnnn JS相关逻辑还未正式开源，目前不做JS相关问题的跟进。
