### ISSUE TITLE
iOS 透明view JS addEventListener 手势不生效

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#444]
**描述这个问题**

iOS 透明view(也没有event, data,track的绑定) 在JS 通过addEventListener 添加事件不生效。原因是内部扁平化导致，该view被移除

**复现步骤**

1. 创建一个透明view(也没有event, data,track的绑定) 
2. 在JS 通过addEventListener 添加事件

**预期正确的结果**

能正确响应手势

**截图**

**客户端 (请填写如下信息)  :**
 - GaiaX SDK版本 [0.4.6]

**Comment by jingcheng1988** [comment]
透明view(也没有event, data,track的绑定)，会默认不进行渲染，如果需要保留view可以在css中增加属性 color: transparent即可
