### ISSUE TITLE
js执行倒计时，生命周期重走导致 gif图片闪烁问题

### ISSUE THREAD

**Issue by youjiaxichenyun** [alibaba/GaiaX#455]
mock 数据
{
    "data": {
        "status": 1,
        "carImage": "https: //cdncc-frontend.caocaokeji.cn/2/dynamic-card-center/passenger/双闪浮层_曹操60_慢闪.webp",
        "downCountMaxTime": 100
    }
}
视频：

[https://cdncc-frontend.caocaokeji.cn/2/test/dynamic/VID_20231019_171638.mp4](url)
demo：
https://cdncc-frontend.caocaokeji.cn/2/test/dynamic/SmartCarDialog.zip

**Comment by biezhihua** [comment]
模板导入错误：js导入错误，整个模板 不是从Gaia Studio导出的，index.js 的内容无法还原

**Comment by youjiaxichenyun** [comment]
[SmartCarDialog.zip](https://github.com/alibaba/GaiaX/files/13052748/SmartCarDialog.zip)
已经重新上传，麻烦在帮忙看下

**Comment by biezhihua** [comment]
@youjiaxichenyun 使用Demo未复现问题
