### ISSUE TITLE
bugly  crash 问题反馈

### ISSUE THREAD

**Issue by youjiaxichenyun** [alibaba/GaiaX#456]
![image](https://github.com/alibaba/GaiaX/assets/20109835/a5ae492f-8ac2-4d6b-80b5-200c802c34dc)

![image](https://github.com/alibaba/GaiaX/assets/20109835/d67587fc-4d8a-4380-93ba-874e14e2ae65)

1
com.alibaba.gaiax.GXTemplateEngine.b(GXTemplateEngine.kt:5)
2
com.alibaba.gaiax.GXTemplateEngine.c(GXTemplateEngine.kt:1)
3
com.alibaba.gaiax.js.adapter.impl.render.GXJSRenderDelegate$setDataToRenderEngine$1.invoke(GXJSRenderDelegate.kt:6)
4
com.alibaba.gaiax.js.adapter.impl.render.GXJSRenderDelegate$setDataToRenderEngine$1.invoke(GXJSRenderDelegate.kt:1)
5
com.youku.gaiax.js.b.f.c(GaiaXJSTaskQueue.kt:1)
6
com.youku.gaiax.js.b.f.d(Unknown Source:0)
7
com.youku.gaiax.js.b.b.run(Unknown Source:2)
8
android.os.Handler.handleCallback(Handler.java:971)
9
android.os.Handler.dispatchMessage(Handler.java:107)
10
android.os.Looper.loopOnce(Looper.java:206)
11
android.os.Looper.loop(Looper.java:296)
12
android.app.ActivityThread.main(ActivityThread.java:9159)
13
java.lang.reflect.Method.invoke(Native Method)
14
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:591)
15
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018)

**Comment by biezhihua** [comment]
@youjiaxichenyun 先反混淆一下。
