### ISSUE TITLE
JS里计算出的高度后，setData不会重新刷新根视图的size

### ISSUE THREAD

**Issue by JohnTsaii** [alibaba/GaiaX#464]
**描述这个问题**
一个view的高度，需要通过js计算得出之后，重新setData刷新extend里的height。这个时候根视图的高度并没有刷新，请问这种情况要如何处理

**复现步骤**
demo里可以直接复现

**预期正确的结果**

请清晰和简明的描述你预期正确的结果。

**截图**

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :
 - 系统: [iOS、Android]
 - GaiaX SDK版本 [0.4.2]

**附加信息**
[testContainer.gaiax.zip](https://github.com/alibaba/GaiaX/files/13578110/testContainer.gaiax.zip)

**Comment by biezhihua** [comment]
main分支没有问题，请更新代码吧
