### ISSUE TITLE
请问是否有计划支持鸿蒙OS？

### ISSUE THREAD

**Issue by lpylinan** [alibaba/GaiaX#477]
请问是否有计划支持鸿蒙OS？
具体的时间节点能否提供？

**Comment by biezhihua** [comment]
有 本周会出个规划

**Comment by biezhihua** [comment]
今天讨论了分工，周三会出一个排期

**Comment by biezhihua** [comment]
![image](https://github.com@lpylinan alibaba/GaiaX/assets/6761107/db188536-81d0-40ac-9182-92b723af2e99)

@
