### ISSUE TITLE
是否支持web端渲染卡片

### ISSUE THREAD

**Issue by yywood123** [alibaba/GaiaX#478]
请问是否支持web端渲染卡片？
如果支持的话，web端该怎么支持渲染；
如果不支持的话，是否有这方面的计划。

**Comment by biezhihua** [comment]
@yywood123 

目前不支持H5渲染。

如果需要支持，可以通过taro的方式来支持，在项目库中已经写了一个taro的基础版本，但是由于优酷不使用，所以未继续推进迭代。
