### ISSUE TITLE
官方文档的模板可视化工具studio不能下载了

### ISSUE THREAD

**Issue by Coldcrack** [alibaba/GaiaX#489]
**描述这个问题**

官方文档的模板可视化工具studio不能下载了
**复现步骤**

可通过分步复现该问题：
https://youku-gaiax.github.io/GaiaXSDK/quick-start.html
官方文档，这个页面的工具不能下载了
![WechatIMG461](https://github.com/user-attachments/assets/430d4792-d1c9-4525-8d54-ffec2c4725f0)

**预期正确的结果**

希望能下载

如果可以的话，添加截图来帮助解释您的问题。

**客户端 (请填写如下信息)  :**
google Chrome

**崩溃日志**
无
**附加信息**
无

**Comment by Coldcrack** [comment]
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/6f2cf027-1e26-44fd-bf37-e1b2352bd515">

**Comment by biezhihua** [comment]
更新了
