### ISSUE TITLE
关于模板异步请求数据

### ISSUE THREAD

**Issue by ljunb** [alibaba/GaiaX#80]
Hi！我们团队之前用的是 `Tangram` ，在其基础上扩展了卡片异步加载的功能。这个有其对应的业务场景，比如某个卡片是定位相关的，需要 App 获取定位后，根据经纬度请求额外信息，再回显到卡片上。

参考之前的做法，我在 `GXDataManager#gx_bindData:onNode:` 做了简单的扩展：
```objc
+ (void)gx_bindData:(NSDictionary *)data onNode:(GXNode *)node {
    ...
    //绑定数据，重新计算布局
    if (node.isRootNode) {
        ...
        // for async load
        [self startAsyncLoadIfNeedForNode:node withOriginalData:data];
    }
}

+ (void)startAsyncLoadIfNeedForNode:(GXNode *)node withOriginalData:(NSDictionary *)rawData {
    // 原数据中补充 load 字段，代表需要异步加载
    if ([rawData[@"load"] length] == 0) return;
    GXTemplateData *templateData = node.templateContext.templateData;
    // 再补充个代理方法
    if (!templateData.dataListener || ![templateData.dataListener respondsToSelector:@selector(gx_asyncLoadDataForKey:completion:)]) {
        return;
    }
    
    [templateData.dataListener gx_asyncLoadDataForKey:rawData[@"load"] completion:^(NSDictionary * _Nullable response) {
        if (response && response.count > 0) {
            NSMutableDictionary *convertedRes = [NSMutableDictionary dictionaryWithDictionary:response ?: @{}];
            // 移除load字段，避免多次触发
            [convertedRes removeObjectForKey:@"load"];
            // TODO：新旧数据合并

            templateData.data = [convertedRes copy];
            [self bindData:templateData onRootNode:node];
        }
    }];
}
```

在 [GaiaXiOSDemo](https://github.com/alibaba/GaiaX/tree/main/GaiaXiOSDemo) 的 `ListViewController` 中添加代理方法，并根据不同的 `load` 模拟异步请求：
```objc
- (void)gx_asyncLoadDataForKey:(NSString *)loadKey completion:(void (^)(NSDictionary * _Nullable))completion {
    // 异步加载的卡片1
    if ([loadKey isEqualToString:@"async_load1"]) {
        dispatch_async(dispatch_get_global_queue(0, 0), ^{
            dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
                completion(@{
                    @"img": @"https://s.xiaopeng.com/xp-app/material/webp/ngp.webp",
                    @"title": @"async title",
                    @"desc": @"我是副标题",
                    @"load": @"asyn_load1"
                });
            });
        });
    } else if ([loadKey isEqualToString:@"async_load2"]) {
        // 异步加载的卡片2
        dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
            completion([GaiaXHelper jsonWithFileName:@"load2"]);
        });
    }
    ...
}
```
目前自己在 Demo 中自测正常，可以达到异步加载目的。今天刚接触这个项目，其实主要有两个疑问：
* 后续是否考虑为模板添加异步请求的功能？
* 我在 Demo 中尝试了支持文本自适应的模板，在异步请求中模拟了超长文本的数据，最后 `bindData` 时模板可以正常自适应高度。不过由于 `ListViewController` 中 `cell` 的高度为手动设置，这时候我没有重新设置高度的话，发现 `cell` 还是保持原来的高度。所以想问下，是否有比较好的方式来处理这种动态高度的场景？

**Comment by biezhihua** [comment]
@jingcheng1988

**Comment by jingcheng1988** [comment]
> Hi！我们团队之前用的是 `Tangram` ，在其基础上扩展了卡片异步加载的功能。这个有其对应的业务场景，比如某个卡片是定位相关的，需要 App 获取定位后，根据经纬度请求额外信息，再回显到卡片上。
> 
> 参考之前的做法，我在 `GXDataManager#gx_bindData:onNode:` 做了简单的扩展：
> 
> ```objc
> + (void)gx_bindData:(NSDictionary *)data onNode:(GXNode *)node {
>     ...
>     //绑定数据，重新计算布局
>     if (node.isRootNode) {
>         ...
>         // for async load
>         [self startAsyncLoadIfNeedForNode:node withOriginalData:data];
>     }
> }
> 
> + (void)startAsyncLoadIfNeedForNode:(GXNode *)node withOriginalData:(NSDictionary *)rawData {
>     // 原数据中补充 load 字段，代表需要异步加载
>     if ([rawData[@"load"] length] == 0) return;
>     GXTemplateData *templateData = node.templateContext.templateData;
>     // 再补充个代理方法
>     if (!templateData.dataListener || ![templateData.dataListener respondsToSelector:@selector(gx_asyncLoadDataForKey:completion:)]) {
>         return;
>     }
>     
>     [templateData.dataListener gx_asyncLoadDataForKey:rawData[@"load"] completion:^(NSDictionary * _Nullable response) {
>         if (response && response.count > 0) {
>             NSMutableDictionary *convertedRes = [NSMutableDictionary dictionaryWithDictionary:response ?: @{}];
>             // 移除load字段，避免多次触发
>             [convertedRes removeObjectForKey:@"load"];
>             // TODO：新旧数据合并
> 
>             templateData.data = [convertedRes copy];
>             [self bindData:templateData onRootNode:node];
>         }
>     }];
> }
> ```
> 
> 在 [GaiaXiOSDemo](https://github.com/alibaba/GaiaX/tree/main/GaiaXiOSDemo) 的 `ListViewController` 中添加代理方法，并根据不同的 `load` 模拟异步请求：
> 
> ```objc
> - (void)gx_asyncLoadDataForKey:(NSString *)loadKey completion:(void (^)(NSDictionary * _Nullable))completion {
>     // 异步加载的卡片1
>     if ([loadKey isEqualToString:@"async_load1"]) {
>         dispatch_async(dispatch_get_global_queue(0, 0), ^{
>             dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
>                 completion(@{
>                     @"img": @"https://s.xiaopeng.com/xp-app/material/webp/ngp.webp",
>                     @"title": @"async title",
>                     @"desc": @"我是副标题",
>                     @"load": @"asyn_load1"
>                 });
>             });
>         });
>     } else if ([loadKey isEqualToString:@"async_load2"]) {
>         // 异步加载的卡片2
>         dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(1.5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
>             completion([GaiaXHelper jsonWithFileName:@"load2"]);
>         });
>     }
>     ...
> }
> ```
> 
> 目前自己在 Demo 中自测正常，可以达到异步加载目的。今天刚接触这个项目，其实主要有两个疑问：
> 
> * 后续是否考虑为模板添加异步请求的功能？
> * 我在 Demo 中尝试了支持文本自适应的模板，在异步请求中模拟了超长文本的数据，最后 `bindData` 时模板可以正常自适应高度。不过由于 `ListViewController` 中 `cell` 的高度为手动设置，这时候我没有重新设置高度的话，发现 `cell` 还是保持原来的高度。所以想问下，是否有比较好的方式来处理这种动态高度的场景？

1. 暂时没有添加异步加载数据的计划，您可以按照业务场景需求进行扩展来达到目标。
2. 由于iOS的tableView/collectionView的机制，您需要通过reload的方式同步更新cell的高度和内容，也就是调用我们提供的计算size的方法和binddata的方式

**Comment by ljunb** [comment]
了解，看来还是业务根据实际情况定制吧
