### ISSUE TITLE
GAIAX studio 新增自定义view ，原生类名消失

### ISSUE THREAD

**Issue by hycoon** [alibaba/GaiaX#9]
GAIAX studio 在新建自定义view即customView 在右侧属性面中填写原生view 类名后，在模版文件中类名消失。

**Comment by biezhihua** [comment]
Gaia Studio 0.1.11已更新
修复无法编辑自定义节点的问题

更新方式：启动Gaia Studio，待右上角有更新提示后，点击自动重启完成更新

![image](https://user-images.githubusercontent.com/6761107/164427208-5e9a58e8-75ed-4ece-b3ca-f1350ecae9b2.png)
